Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: ap-south-1a
      ImageId: ami-052cef05d01020f1d
      InstanceType: t2.micro
      KeyName: key
      Tags:
        - Name: dev-box