Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-052cef05d01020f1d
      InstanceType: t2.micro
      SecurityGroups: 
        - !Ref SSHSecurityGroup
        - !Ref ServerSecurityGropu