AWSTemplateFormatVersion: "2010-09-09"
Resources:
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/" 
      Roles: 
        - "cloudFormationAccess"

  FirstEC2instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-052cef05d01020f1d
      InstanceType:  t2.micro
      IamInstanceProfile: !Ref InstanceProfile


