AWSTemplateFormatVersion: "2010-09-09"
Description: "to create IAM role, Group and User for an EC2 instance"
Resources: 
    IAMRole1: 
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                        Service:
                            - ec2.amazonaws.com
                      Action: 
                        - 'sts:AssumeRole'
            Policies:
                - PolicyName: ec2Access
                  PolicyDocument: 
                    Version: "2012-10-17"
                    Statement: 
                        - 
                            Effect: "Allow"
                            Action: "*"
                            Resource: "*"
    
    MyInstanceProfile: 
        Type: "AWS::IAM::InstanceProfile"
        Properties: 
            Path: "/"
            Roles: 
                - 
                    Ref: "IAMRole1"
    
